{
 "title": "Hiking App Dashboard",
 "tags": [
  "spring boot",
  "prometheus",
  "hiking"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP 5xx Error Rate (%)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) / sum(rate(http_server_requests_seconds_count[5m])))"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate (by URI)",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Avg Response Time (seconds)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m])) by (uri) / sum(rate(http_server_requests_seconds_count[1m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "JVM Heap Used (MB)",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 8, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "stat",
   "gridPos": { "x": 18, "y": 8, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_usage * 100" }
   ]
  },
  {
   "title": "GC Pause Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[5m])"
    }
   ]
  }
 ]
}